# Generated by Django 3.0 on 2019-12-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('ha1', models.CharField(max_length=128)),
                ('ha1b', models.CharField(max_length=128)),
            ],
        ),
    ]
